export declare const lunarInfo: number[];
export declare const zodiacs: string[];
export declare const Gan: string[];
export declare const Zhi: string[];
export declare const weekday: string[];
export declare const sTermInfo: number[];
export declare const solarTerm: string[];
export declare const cnStr1: string[];
export declare const cnStr2: string[];
